import { NextFunction, Request, Response } from "express"
import * as jwt from "jsonwebtoken"

import { isString } from "util"
import {
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  PERIL_WEBHOOK_SECRET,
  PRIVATE_GITHUB_SIGNING_KEY,
  PUBLIC_API_ROOT_URL,
  PUBLIC_GITHUB_SIGNING_KEY,
} from "../../globals"
import { GitHubOAuthEnd } from "../api"
import fetch from "../fetch"

// A JWT is a special type of string
type JWT = string

// The Decoded JWT data
export interface PerilJWT {
  exp: number
  iat: number
  iss: string[]
  data: {
    gh_orgs: GHOrg[]
    user: PerilOAuthUser
  }
}

export interface PerilOAuthUser {
  name: string
  avatar_url: string
}

/**
 * Takes a user with details from GH Oauth and generates
 * a JWT which can be used to make authenticated requests
 * against Peril.
 */
export const createPerilJWT = (user: PerilOAuthUser, gitHubOrgs: GHOrg[]): JWT => {
  const now = Math.round(new Date().getTime() / 1000)
  const expires = now + 60
  const keyContent = PRIVATE_GITHUB_SIGNING_KEY
  const payload: PerilJWT = {
    exp: expires,
    iat: now,
    iss: [user.name, ...gitHubOrgs.map(o => o.login)],
    data: {
      gh_orgs: gitHubOrgs,
      user,
    },
  }

  return jwt.sign(payload, keyContent, { algorithm: "RS256" })
}

/**
 * Decode and verifies a JWT generated by createPerilJWT above
 * @param token the JWT
 */
export const getDetailsFromPerilJWT = (token: JWT) =>
  new Promise<PerilJWT>((res, rej) => {
    const options = { algorithms: ["RS256"] }

    jwt.verify(token, PUBLIC_GITHUB_SIGNING_KEY, options, (err, decoded) => {
      if (err) {
        rej(err)
      } else {
        if (isString(decoded)) {
          res(JSON.parse(decoded as string))
        } else {
          res(decoded as any)
        }
      }
    })
  })

/** { a: 1, b: 2} -> a=1&=2 */
const encodeToQueryParams = (data: any): string =>
  Object.keys(data)
    .map(key => {
      return [key, data[key]].map(encodeURIComponent).join("=")
    })
    .join("&")

/** Handle sending someone off to GitHub for the start of OAuth */
export const redirectForGHOauth = (_: Request, res: Response, ___: NextFunction) => {
  // Re-direct for GH web flow
  // https://developer.github.com/apps/building-oauth-apps/authorization-options-for-oauth-apps/#web-application-flow
  //
  const gh = "https://github.com/login/oauth/authorize"
  const params = {
    client_id: GITHUB_CLIENT_ID,
    // TODO: This URL needs to also contain the value to return to for peril's admin UI also
    redirect_uri: PUBLIC_API_ROOT_URL + GitHubOAuthEnd,
    scope: "read:user",
    state: PERIL_WEBHOOK_SECRET,
  }

  res.redirect(`${gh}?${encodeToQueryParams(params)}`)
}

export const generateAuthToken = async (req: Request, res: Response, ___: NextFunction) => {
  // https://developer.github.com/apps/building-oauth-apps/authorization-options-for-oauth-apps/#2-users-are-redirected-back-to-your-site-by-github

  // Receive the GH auth token, then generate enough info for a Peril User & JWT
  // Set that to the user's session, and then redirect to the admin page
  const { code, state } = req.params
  if (state !== PERIL_WEBHOOK_SECRET) {
    // NOOP
    return
  }
  const token = await getAccessTokenFromAuthCode(code)

  const orgs = await getUserOrgs(token)
  const user = await getUserAccount(token)

  const authToken = createPerilJWT({ name: user.name, avatar_url: user.avatar_url }, orgs)
  res.cookie("jwt", authToken)
}

const getAccessTokenFromAuthCode = async (code: string) => {
  const gh = "https://github.com/login/oauth/access_token"
  const options = {
    headers: {
      Accept: "application/json",
    },
  }
  const params = {
    client_id: GITHUB_CLIENT_ID,
    client_secret: GITHUB_CLIENT_SECRET,
    state: PERIL_WEBHOOK_SECRET,
    code,
  }

  const tokenResponse = await fetch(`${gh}?${encodeToQueryParams(params)}`, options)
  const tokenJSON = await tokenResponse.json()
  return tokenJSON.access_token
}

const getUserAccount = async (token: string) => miniGHAPI(token, "/user")

interface GHOrg {
  login: string
  description: string
  id: number
}

const getUserOrgs = async (token: string): Promise<GHOrg[]> => {
  const orgs = await miniGHAPI("/user/orgs", token)
  return orgs.map((o: any) => ({
    login: o.login,
    description: o.description,
    id: o.id,
  }))
}

const miniGHAPI = async (path: string, token: string) => {
  const gh = "https://api.github.com/" + path

  const options = {
    headers: {
      Accept: "application/json",
    },
  }
  const params = {
    access_token: token,
  }

  const userResponse = await fetch(`${gh}?${encodeToQueryParams(params)}`, options)
  return await userResponse.json()
}
