FROM node:9.11-slim

ADD . /app
WORKDIR /app

ENV COMMIT_SHA=$(git rev-parse HEAD)

# This will also trigger the build process
RUN yarn install

# TODO: Get the additional node modules installed
RUN node out/scripts/hyper/install-hyper-deps.js
