FROM node:8.9-slim

ADD . /app
WORKDIR /app

# This will also trigger the build process
RUN yarn install

# TODO: Get the additional node modules installed
RUN node out/scripts/hyper/install-hyper-deps.js