FROM node:9.11-slim

ADD . /app
WORKDIR /app

ARG SOURCE_COMMIT
ENV SOURCE_COMMIT $SOURCE_COMMIT

# This will also trigger the build process
RUN yarn install

# TODO: Get the additional node modules installed
RUN node out/scripts/hyper/install-hyper-deps.js
