FROM node:10-slim

MAINTAINER Orta Therox
ARG BRANCH="master"
ARG COMMIT=""
LABEL branch=${BRANCH}
LABEL commit=${COMMIT}

ADD . /app
WORKDIR /app

# Now set it as an env var
ENV COMMIT_SHA=${COMMIT}

# This will also trigger the build process
RUN yarn install

# Get the additional node modules installed
RUN node out/scripts/hyper/install-hyper-deps.js
